header_pages:
  - index.markdown
  - projects.markdown
  - about.markdown
  
title: Lukas Kubinec
email: Luko.Kubinec@gmail.com
description: Software & Games developer | Grad student Edge Hill University UK.
url:

theme: minima

minima:
  skin: solarized-dark
  hide_site_feed_link: true
  social_links:
    - title: GitHub
      icon: github
      url: "https://lukas-kubinec.github.io/"
    - title: LinkedIn
      icon: linkedin-in
      url: "https://www.linkedin.com/in/lukaskubinec/"
    - title: ItchIo
      icon: itch-io
      url: "https://lukey-uk.itch.io/"


# remote_theme: jekyll/minima

linkedin: lukaskubinec

plugins:
  - jekyll-feed
  - jekyll-admin
